_wandb:
    value:
        cli_version: 0.23.0
        code_path: source-Sudoku-extreme-1k-aug-1000-ACT-torch-pretrain.py
        e:
            dkjzmft8fc9g9b581ka634titvtxpyk5:
                args:
                    - arch=varc_vit_standard
                    - data_paths=[data/sudoku-extreme-1k-aug-1000]
                    - evaluators=[]
                    - epochs=50000
                    - eval_interval=5000
                    - lr=1e-4
                    - puzzle_emb_lr=1e-4
                    - weight_decay=1.0
                    - puzzle_emb_weight_decay=1.0
                    - grad_clip_norm=-1.0
                    - run_name=pretrain_sudoku-varc_vit_standard
                    - ema=True
                codePath: pretrain.py
                codePathLocal: pretrain.py
                email: Maxwell-Gao314@outlook.com
                executable: /home/maxwell/VirtualRecursiveNetwork/.venv/bin/python
                git:
                    commit: ccec6e9239c8e69142900d18fef5ea37524470ab
                    remote: https://github.com/maxwell-gao/VirtualRecursiveNetwork.git
                host: instance-20251202-130510-20251205-052007
                os: Linux-5.10.0-36-cloud-amd64-x86_64-with-glibc2.31
                program: /home/maxwell/VirtualRecursiveNetwork/pretrain.py
                python: CPython 3.11.14
                root: /home/maxwell/VirtualRecursiveNetwork
                startedAt: "2025-12-15T09:09:30.227056Z"
                writerId: dkjzmft8fc9g9b581ka634titvtxpyk5
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 41
                - 50
                - 106
            "2":
                - 1
                - 41
                - 50
                - 106
            "3":
                - 13
                - 16
                - 61
            "4": 3.11.14
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
arch:
    value:
        act_enabled: false
        act_inference: false
        depth: 6
        dropout: 0
        expansion: 2
        forward_dtype: bfloat16
        halt_exploration_prob: 0
        halt_max_steps: 1
        hidden_size: 256
        loss:
            loss_type: stablemax_cross_entropy
            name: losses@ACTLossHead
        name: vision_reasoning.varc_vit@VARCViT
        num_heads: 8
        patch_size: 3
        puzzle_emb_ndim: 0
beta1:
    value: 0.9
beta2:
    value: 0.95
checkpoint_every_eval:
    value: true
checkpoint_path:
    value: checkpoints/Sudoku-extreme-1k-aug-1000-ACT-torch/pretrain_sudoku-varc_vit_standard
data_paths:
    value:
        - data/sudoku-extreme-1k-aug-1000
data_paths_test:
    value: []
early_stopping:
    value: false
early_stopping_min_delta:
    value: 0
early_stopping_mode:
    value: max
early_stopping_monitor:
    value: exact_accuracy
early_stopping_patience:
    value: 3
ema:
    value: true
ema_rate:
    value: 0.999
epochs:
    value: 50000
eval_interval:
    value: 5000
eval_save_outputs:
    value: []
evaluators:
    value: []
freeze_weights:
    value: false
global_batch_size:
    value: 768
grad_clip_norm:
    value: -1
load_checkpoint:
    value: null
lr:
    value: 0.0001
lr_min_ratio:
    value: 1
lr_warmup_steps:
    value: 2000
min_eval_interval:
    value: 0
muon_lr:
    value: 0.002
muon_momentum:
    value: 0.95
muon_nesterov:
    value: true
muon_ns_steps:
    value: 5
muon_weight_decay:
    value: 0.01
optimizer:
    value: adam_atan2
project_name:
    value: Sudoku-extreme-1k-aug-1000-ACT-torch
puzzle_emb_lr:
    value: 0.0001
puzzle_emb_weight_decay:
    value: 1
run_name:
    value: pretrain_sudoku-varc_vit_standard
seed:
    value: 0
weight_decay:
    value: 1
